wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1677410296.87723
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.7
      5: 0.13.10
      8:
      - 1
      - 2
      - 5
